# Utiliser une image de base Python
FROM python:3.11-slim

# Installer les dépendances nécessaires
RUN apt-get update && apt-get install -y \
    ffmpeg \
    git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Créer un répertoire de travail
WORKDIR /app

# Installer Whisper et PyTorch
RUN pip install -U openai-whisper \
    torch torchvision torchaudio

# Copier un fichier d'entrée audio dans le conteneur (optionnel)

# Copier les fichiers requirements.txt et whisper-audio.py dans le conteneur
COPY whisper-audio.py whisper-audio.py



# Définir la commande par défaut
ENTRYPOINT ["python", "whisper-audio.py"]