FROM python:3.11-slim

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers requirements.txt et retrieve-audio.py dans le conteneur
COPY requirements.txt requirements.txt
COPY retrieve-audio.py retrieve-audio.py

# Installer les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Installer ffmpeg
RUN apt-get update && apt-get install -y ffmpeg

# Définir la commande par défaut
ENTRYPOINT ["python", "retrieve-audio.py"]